spring:
    profiles:
        include:
            - test
            - prod

---

spring:
    profiles: test

server:
    port: 4000

welcomeMsg: "Hello from Test"

---

spring:
    profiles: prod

server:
    port: 5000

welcomeMsg: "Hello from Prod"